name: Listing S3 bucket

on: 
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  listing-s3-buckets:  
    runs-on: ubuntu-latest
    steps:
      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          

      - name: List S3 buckets
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          echo "Listing S3 buckets..."
          aws s3 ls
          echo "S3 buckets listed successfully."

          
  