name: Listing S3 buckets

on: 
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  listing_buckets:  
    runs-on: ubuntu-latest
    steps:
      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
        
      - name: List S3 Buckets 
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          echo "Listing S3 buckets in region: $AWS_REGION"
          aws s3 ls
          
          
  